logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.security: DEBUG
    org.keycloak: DEBUG

app:
  base-url: http://localhost:8080
  complete-registration-url: ${app.base-url}/api/register
  keycloak-client-id: spring-security
  keycloak-client-secret: 342a09be-808a-4b65-90d0-a79f2de45048
  keycloak-issuer-uri: http://localhost:7080/auth/realms/demo

adapter:
  db:
    host: localhost
    port: 3306
    db-name: test
    admin-username: root
    admin-password: root
    standard-username: basic
    standard-password: basic

  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans
