logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.security: DEBUG
    org.keycloak: DEBUG

app:
  base-url: http://localhost:8080
  confirm-registration-url: ${app.base-url}/api/register

adapter:
  db:
    host: localhost
    port: 3306
    db-name: test
    admin-username: root
    admin-password: root
    standard-username: basic
    standard-password: basic
  redis:
    host: localhost
    port: 6379
  keycloak:
    base-url: http://localhost:7080/auth
    issuer-url: ${adapter.keycloak.base-url}/realms/demo
    client-id: spring-security
    client-secret: 342a09be-808a-4b65-90d0-a79f2de45048
    realm: demo
    admin-client-id: admin-cli
    admin-username: admin
    admin-password: admin
    admin-realm: master

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans
