version: '3.1'
services:

  # To import the schema, run ./src/main/docker/import-schema.sh
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 9080:8080

  redis:
    image: redis
    ports:
      - 6379:6379

#  redis-commander:
#    image: rediscommander/redis-commander
#    ports:
#      - 8081:8081
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379

  keycloak:
    image: jboss/keycloak
    volumes:
      - ./keycloak/demo-realm.json:/tmp/demo-realm.json
    ports:
      - 7080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/demo-realm.json
