version: '3.1'
services:

#  demo-app:
#    image: demo-app:0.0.1-SNAPSHOT
#    ports:
#      - 8080:8080
#    restart: always
#    depends_on:
#      - db
#      - redis
#      - keycloak

  # To import the schema, run ./src/main/docker/import-schema.sh
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 9080:8080

  redis:
    image: redis:6.0.8
    ports:
      - 6379:6379

#  redis-commander:
#    image: rediscommander/redis-commander
#    ports:
#      - 8081:8081
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379

  keycloak:
    image: jboss/keycloak:11.0.2
    volumes:
      - ./keycloak/demo-realm.json:/tmp/demo-realm.json
    ports:
      - 7080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/demo-realm.json
