openapi: 3.0.1
info:
  title: Demo Application
  description: This is a demo application
  termsOfService: http://swagger.io/terms/
  contact:
    email: tomas.jakubco@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/register:
    post:
      tags:
        - register
      summary: Starts the registration process
      operationId: beginRegistration
      requestBody:
        description: Registration details payload
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      responses:
        200:
          description: Returns the unique temporary url
          content:
            text/plain:
              schema:
                type: string
        400:
          description: Bad request
          content: {}
  /api/register/{uuid}:
    post:
      tags:
        - register
      summary: Completes the registration process
      operationId: completeRegistration
      parameters:
        - name: uuid
          in: path
          description: UUID of the registration
          required: true
          schema:
            type: string
      responses:
        201:
          description: User is registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad request
          content: {}
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Register:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
